### ISSUE TITLE
Feature: User can answer trivia questions.

### ISSUE THREAD

**Issue by mikejglenn** [mikejglenn/open-trivia#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can answer trivia questions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can start a new game then answer trivia questions. The can select multiple choice answers or true/false answers depending on the questions.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="138" alt="image" src="https://github.com/user-attachments/assets/c1520bfc-6458-40d2-9100-e2b4879ea461">
<img width="140" alt="image" src="https://github.com/user-attachments/assets/18c724b7-b8d3-4fc0-9772-61f44b7262b5">
<img width="140" alt="image" src="https://github.com/user-attachments/assets/a762eabb-ace1-4b1f-ad03-4588d8656589">
<img width="137" alt="image" src="https://github.com/user-attachments/assets/8dc46359-6f74-4683-84c5-2b24ca020c04">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] HTML skeleton
- [x] CSS for skeleton elements
- [x] Data model of trivia game
- [x] Read and write localStorage
- [x] New trivia game creation
- [x] API call for trivia question
- [x] Render question and answers
- [x] Determine if answer is correct or incorrect
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
